### PR TITLE
Pin fsevents to 1.2.4 to fix osx installation.

### LINKED ISSUE #1999: `fsevents@1.1.2` dependency doesn't compile on OSX, node@10.1.0, breaking package
### Describe the problem and steps to reproduce it:
1. Make sure you're running on OSX and have NodeJS 10.x installed.
2. Run `npm install addons-linter`.
3. Watch it fail to install `fsevents` due to a compilation error due to breaking V9 header changes.

The solution is to have your dependencies upgraded to `fsevents@1.2.4` and all will be fine again.
However, npm isn't smart enough anymore to tell me which package pinned the wrong version and going through the list of dependencies by hand is going to take a long, long, long time.

I fixed it locally to install 1.2.4 manually in the project root and from there all is fine again; it can be worked around.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #1999

```
arn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Well… let me find out what the heck is going on here. This is just stupid, one version doesn't support osx, the other doesn't support linux :man_shrugging:

**Comment by EnTeQuAk** [comment]
Regarding the snyk failure, there's a PR that started work towards getting rid of this library. It's unrelated to this work here.
