### ISSUE TITLE
`fsevents@1.1.2` dependency doesn't compile on OSX, node@10.1.0, breaking package

### ISSUE THREAD

**Issue by mikedeboer** [mozilla/addons-linter#1999]
### Describe the problem and steps to reproduce it:
1. Make sure you're running on OSX and have NodeJS 10.x installed.
2. Run `npm install addons-linter`.
3. Watch it fail to install `fsevents` due to a compilation error due to breaking V9 header changes.

The solution is to have your dependencies upgraded to `fsevents@1.2.4` and all will be fine again.
However, npm isn't smart enough anymore to tell me which package pinned the wrong version and going through the list of dependencies by hand is going to take a long, long, long time.

I fixed it locally to install 1.2.4 manually in the project root and from there all is fine again; it can be worked around.

**Comment by EnTeQuAk** [comment]
It seems to be pinned by a sub-dependency of a dependency of webpack. I'll try to pin us to `fsevents@1.2.4` and see how that goes.

Thanks a lot for the report!

**Comment by EnTeQuAk** [comment]
Okay, looking at #2029 this doesn't seem that easy, needs more investigation.

**Comment by wagnerand** [comment]
It's interesting that using yarn does not raise that error for me.

**Comment by EnTeQuAk** [comment]
It does for me :thinking:

**Comment by AlexandraMoga** [comment]
Could you please add a 'qa:not needed' label?
Thank you
